accountLinking:
  enableAccountCreation: true
  linkingType: GOOGLE_SIGN_IN
category: GAMES_AND_TRIVIA
defaultLocale: es
localizedSettings:
  developerEmail: j.alban@uniandes.edu.co
  developerName: Juan José Albán Ortiz
  displayName: Torre Assistant
  fullDescription: The assistant that will give you information about the best job
    listings for you on torre.co
  privacyPolicyUrl: https://torre.co/privacy
  pronunciation: Torre Assistant
  shortDescription: best jobs for you.
  termsOfServiceUrl: https://torre.co/terms
projectId: torre-assistant
usesInteractiveCanvas: true
