category: GAMES_AND_TRIVIA
defaultLocale: es
localizedSettings:
  developerEmail: j.alban@uniandes.edu.co
  developerName: Juan José Albán
  displayName: Torre Assistant
  fullDescription: The assistant that will show you the best jobs for you, daily and every time you ask. It will show you the bestfor category for your jobs
  privacyPolicyUrl: torre.co/privacy
  pronunciation: Torre Assistant
  shortDescription: The assistant that will help you to find a job.
  smallLogoImage: https://lh3.googleusercontent.com/V93nlV0TabIb-C583kgrPye3Crh974SUDtEytrn6yD9sp8TihAMfiVcURdrpkHWWDI7cByB4OXKS
  termsOfServiceUrl: torre.co/terms
projectId: torre-assistant
